export const halls = [
     {
    name:"Bethel Atlanta Auditorium",
    country:"Cameroon",
    isVerified:true,
    owner:"Betthel Atlanta",
    city:"Buea",
    address:"Buea town, Buea",
    hasCarParkingSpace:true,
    hallArea:"900 square meters",
    locationDescription:"Opposite Bilingual grammar schools CheckPoint Molyko. By the road and very accessible.",
    hasSecurity:true,
    phoneNumber:"+237675604750",
    pricing:[
        ['Hall','200000'],
        ['Caution','20000'],
        ['Hall Cleaning','25000'],
        ['1 Chair','500'],
        ['Generator','10000'],
    ],
    rating:4,
    email:"",
    images:["WhatsApp Image 2023-07-21 at 12.08.00(1).jpeg", "WhatsApp Image 2023-07-21 at 12.08.00.jpeg"],
    capacity:"200",
},
    {
        name:"St.Charles Lwanga Hall",
        country:"Cameroon",
        isVerified:true,
        owner:"St.Charles Lwanga Catholic Church",
        city:"Buea",
        address:"CheckPoint Molyko Buea",
        hasCarParkingSpace:true,
        hallArea:"900 square meters",
        locationDescription:"Opposite Bilingual grammar schools CheckPoint Molyko. By the road and very accessible.",
        hasSecurity:true,
        phoneNumber:"+237675604750",
        pricing:[
            ['Hall','200000'],
            ['Caution','20000'],
            ['Hall Cleaning','25000'],
            ['1 Chair','500'],
            ['Generator','10000'],
        ],
        rating:3,
        email:"",
        images:["CharlesLwanga1.jpg","CharlesLwanga2.jpg"],
        capacity:"1000",
    },
   
    {
        name:"Frida Farms Banquet Hall",
        country:"Cameroon",
        isVerified:true,
        city:"Buea",
        owner:"Frida Farms",
        address:"Bunduma Gate Buea",
        hasCarParkingSpace:false,
        hallArea:"600 square meters",
        locationDescription:"The hall is located 150 meters from Bunduma gate junction just before the public tap",
        hasSecurity:true,
        phoneNumber:"+237672859171",
        rating:3,
        pricing:[
            ['Hall + 500 chairs and tables','350000'],
            ['Caution','50000'],
            ['Post event Cleaning','25000'],
            ['1 Chair','500'],
            ['Generator','25000'],
            ['Projector','25000'],
            ['Basic Decor','150000'],
            ["Couple's chair",'40000'],
        ],
        email:"",
        images:["fridafarms1.jpg","Fridafarms2.jpg","Fridafarms3.jpg"],
        capacity:"400",
    },    {
        name:"Frida Farms White Hall",
        country:"Cameroon",
        isVerified:false,
        city:"Buea",
        owner:"Frida Farms",
        address:"Bunduma Gate Buea",
        hasCarParkingSpace:false,
        hallArea:"600 square meters",
        locationDescription:"The hall is located 150 meters from Bunduma gate junction just before the public tap",
        hasSecurity:true,
        phoneNumber:"+237672859171",
        rating:4,
        pricing:[
            ['Hall + 500 chairs and tables','350000'],
            ['Caution','50000'],
            ['Post event Cleaning','25000'],
            ['1 Chair','500'],
            ['Generator','25000'],
            ['Projector','25000'],
            ['Basic Decor','150000'],
            ["Couple's chair",'40000'],
        ],
        email:"",
        images:["Fridafarms2.jpg","fridafarms1.jpg","Fridafarms3.jpg"],
        capacity:"120",
    },    {
        name:"Frida Farms Conference Hall",
        country:"Cameroon",
        isVerified:false,
        city:"Buea",
        owner:"Frida Farms",
        address:"Bunduma Gate Buea",
        hasCarParkingSpace:false,
        hallArea:"600 square meters",
        locationDescription:"The hall is located 150 meters from Bunduma gate junction just before the public tap",
        hasSecurity:true,
        phoneNumber:"+237672859171",
        rating:4,
        pricing:[
            ['Hall + 500 chairs and tables','350000'],
            ['Caution','50000'],
            ['Post event Cleaning','25000'],
            ['1 Chair','500'],
            ['Generator','25000'],
            ['Projector','25000'],
            ['Basic Decor','150000'],
            ["Couple's chair",'40000'],
        ],
        email:"",
        images:["Fridafarms3.jpg","fridafarms1.jpg","Fridafarms2.jpg"],
        capacity:"26",
    },   {
        name:"Frida Farms OutDoor space",
        country:"Cameroon",
        isVerified:true,
        city:"Buea",
        owner:"Frida Farms",
        address:"Bunduma Gate Buea",
        hasCarParkingSpace:false,
        hallArea:"600 square meters",
        locationDescription:"The hall is located 150 meters from Bunduma gate junction just before the public tap",
        hasSecurity:true,
        phoneNumber:"+237672859171",
        rating:3,
        pricing:[
            ['Hall + 500 chairs and tables','350000'],
            ['Caution','50000'],
            ['Post event Cleaning','25000'],
            ['1 Chair','500'],
            ['Generator','25000'],
            ['Projector','25000'],
            ['Basic Decor','150000'],
            ["Couple's chair",'40000'],
        ],
        email:"",
        images:[],
        capacity:"30",
    },   {
        name:"Frida Farms Pent House",
        country:"Cameroon",
        isVerified:false,
        city:"Buea",
        owner:"Frida Farms",
        address:"Bunduma Gate Buea",
        hasCarParkingSpace:false,
        hallArea:"600 square meters",
        locationDescription:"The hall is located 150 meters from Bunduma gate junction just before the public tap",
        hasSecurity:true,
        phoneNumber:"+237672859171",
        rating:4,
        pricing:[
            ['Hall + 500 chairs and tables','350000'],
            ['Caution','50000'],
            ['Post event Cleaning','25000'],
            ['1 Chair','500'],
            ['Generator','25000'],
            ['Projector','25000'],
            ['Basic Decor','150000'],
            ["Couple's chair",'40000'],
        ],
        email:"",
        images:[],
        capacity:"32",
    },
]